### PR TITLE
Highlighting refinements

### LINKED ISSUE #10: Some characters are not highlighted as part of a token
Although the subscript one character `₁` is not highlighted as part of the preceding token, the typechecker considers it part of it. This is because `\b` matches here when it shouldn't:

image

A couple of other characters with the same behavior are `-+*`.

To fix this, I suggest writing custom patterns for matching word boundaries instead of using `\b`. As a start, here are the ones I use for Agda code:

- `(?<=^|\\{\\!|\\{-\\#|[\\s.;{}()@\"])` for left boundaries
- `(?=$|\\!\\}|[\\s.;{}()@\"])` for right boundaries

You probably don't want the hole or pragma parts, and also, maybe you don't want commas and some other characters in tokens. Hence I'll suggest the following:

1. `(?<=^|[\\s.,;{}()<>@\"\\\\_|])` for left boundaries
2. `(?=$|[\\s.,;{}()<>@\"\\\\_|])` for right boundaries

### LINKED ISSUE #12: Some builtin constructs don't highlight as such when given implicit argument
See image below for an example :)

image

### PR DESCRIPTION
**Pull request by fredrik-bakke**
Sorry, I couldn't help myself. This adds a bunch of highlighting to things like different punctuation and refines boundaries. Resolves #10 and resolves #12.

### CODE REVIEW

**Comment by fizruk** [comment]
Thanks for this! Unfortunately, it seems that although you have fixed some things, a few problems remain and some new problems sneaked in:
- introduction of bound variables in lambda abstractions and Sigma-types are not highlighted anymore
- some constants (e.g. `0_1`, `0_2`) are not always highlighted
- built-ins `first`, `second`, `refl`, `recBOT` are now highlighted as names of definitions
- nested Sigma-types still have differently highlighted Sigma symbols (e.g. see [`isSegal'-isSegal`](https://github.com/emilyriehl/yoneda/blob/8b1e639451a78ee913d72b75ee5885206dfb04ca/src/simplicial-hott/05-segal-types.rzk.md?plain=1#L304-L305) in the emilyriehl/yoneda repository)

**Comment by fredrik-bakke** [comment]
Ah, thanks for the feedback!
I'll have a look at the issues sometime next week I think. I primarily posted the PR as I already had some half-baked code.

**Comment by fizruk** [comment]
Take your time! We hope to get semantic highlighting working by next week in #15, but TextMate grammar is still useful as a fallback highlighting.

**Comment by fizruk** [comment]
I've tested this fix together with #5 and https://github.com/fizruk/rzk/pull/53, and it seems ok. Sigmas are still highlighted differently (e.g. see lines 296–297 below), but it can be fixed later. This is what it looks like now:

Screenshot 2023-06-20 at 11 14 31

I am merging this.

**Pull request merged**
